// World Cup 2026 — 48 teams with approximate strength ratings (Elo-like, 0-100 scale).
// Ratings are rough estimates for simulation purposes only, not official rankings.
const TEAMS = [
  { name: "Argentina", flag: "🇦🇷", rating: 94 },
  { name: "France", flag: "🇫🇷", rating: 93 },
  { name: "Brazil", flag: "🇧🇷", rating: 92 },
  { name: "England", flag: "🇬🇧", rating: 90 },
  { name: "Spain", flag: "🇪🇸", rating: 91 },
  { name: "Portugal", flag: "🇵🇹", rating: 88 },
  { name: "Netherlands", flag: "🇳🇱", rating: 87 },
  { name: "Belgium", flag: "🇧🇪", rating: 83 },
  { name: "Germany", flag: "🇩🇪", rating: 86 },
  { name: "Italy", flag: "🇮🇹", rating: 84 },
  { name: "Croatia", flag: "🇭🇷", rating: 82 },
  { name: "Uruguay", flag: "🇺🇾", rating: 81 },
  { name: "Colombia", flag: "🇨🇴", rating: 80 },
  { name: "Morocco", flag: "🇲🇦", rating: 80 },
  { name: "USA", flag: "🇺🇸", rating: 78 },
  { name: "Mexico", flag: "🇲🇽", rating: 77 },
  { name: "Switzerland", flag: "🇨🇭", rating: 79 },
  { name: "Denmark", flag: "🇩🇰", rating: 78 },
  { name: "Senegal", flag: "🇸🇳", rating: 77 },
  { name: "Japan", flag: "🇯🇵", rating: 79 },
  { name: "South Korea", flag: "🇰🇷", rating: 76 },
  { name: "Ecuador", flag: "🇪🇨", rating: 76 },
  { name: "Austria", flag: "🇦🇹", rating: 76 },
  { name: "Iran", flag: "🇮🇷", rating: 73 },
  { name: "Australia", flag: "🇦🇺", rating: 72 },
  { name: "Canada", flag: "🇨🇦", rating: 73 },
  { name: "Egypt", flag: "🇪🇬", rating: 73 },
  { name: "Tunisia", flag: "🇹🇳", rating: 72 },
  { name: "Algeria", flag: "🇩🇿", rating: 73 },
  { name: "Ivory Coast", flag: "🇨🇮", rating: 74 },
  { name: "Ghana", flag: "🇬🇭", rating: 70 },
  { name: "Nigeria", flag: "🇳🇬", rating: 71 },
  { name: "Cameroon", flag: "🇨🇲", rating: 70 },
  { name: "South Africa", flag: "🇿🇦", rating: 69 },
  { name: "Saudi Arabia", flag: "🇸🇦", rating: 69 },
  { name: "Qatar", flag: "🇶🇦", rating: 67 },
  { name: "Jordan", flag: "🇯🇴", rating: 65 },
  { name: "Uzbekistan", flag: "🇺🇿", rating: 65 },
  { name: "New Zealand", flag: "🇳🇿", rating: 64 },
  { name: "Panama", flag: "🇵🇦", rating: 68 },
  { name: "Costa Rica", flag: "🇨🇷", rating: 68 },
  { name: "Jamaica", flag: "🇯🇲", rating: 65 },
  { name: "Haiti", flag: "🇭🇹", rating: 62 },
  { name: "Curaçao", flag: "🇨🇼", rating: 60 },
  { name: "Paraguay", flag: "🇵🇾", rating: 71 },
  { name: "Venezuela", flag: "🇻🇪", rating: 70 },
  { name: "Scotland", flag: "🇬🇧", rating: 74 },
  { name: "Poland", flag: "🇵🇱", rating: 75 },
];
